 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package utils;

/**
 *
 * @author pedro
 */
public class Mensajes {
    
    //Mensaje de login prueba
    public final static String LOGIN_PRUEBA = "PETICIONLOGIN";
    public final static String PETICION_MAPA_LUDOTECAS ="PETICIONMAPALUDOTECAS";
    public final static String PETICION_MAPA_LUDOTECAS_CORRECTA="PETICIONMAPALUDOTECASCORRECTA";
    
    
    
    
    
    //Mensajes Reales
    //MENSAJES DEL SERVIDOR
    //PETICIONES
    public final static String PETICION_LOGIN = "P1LOGIN";
    public final static String PETICION_CREAR_PROPIETARIO = "P2ADDPROPIETARIO";
    public final static String PETICION_CREAR_LUCOTECA = "P3ADDLUDOTECA";
    public final static String PETICION_MOSTRAR_PROPIETARIOS = "P4SHOWPROPIETARIOS";
    public final static String PETICION_ELIMINAR_PROPIETARIO = "P5DELETEPROPIETARIO";
    public final static String PETICION_MOSTRAR_LUDOTECAS = "P6SHOWLUDOTECAS";
    public final static String PETICION_MOSTRAR_LUDOTECAS_POR_PROPIETARIO = "P7SHOWLUDOTECASPROPIETARIO";
    public final static String PETICION_MOSTRAR_EMPLEADOS_POR_LUDOTECA = "P8SHOWEMPLEADOSPORLUDOTECA";
    public final static String PETICION_MOSTRAR_EDITAR_PROPIETARIO = "P9SHOWEDITPROPIETARIO";  
    public final static String PETICION_EDITAR_PROPIETARIO = "P10EDITPROPIETARIO";
    public final static String PETICION_NOMBRE_PROPIETARIO = "P11OBTENERNOMBREPROPIETARIO";
    public final static String PETICION_INFORMACION_PROPIETARIO = "P12INFORMACIONPROPIETARIO";
    public final static String PETICION_ELIMINAR_LUDOTECA = "P13DELETELUDOTECA";
    public final static String PETICION_MOSTRAR_SALAS_POR_LUDOTECA = "P14SHOWROOMXLUDOTECA";
    public final static String PETICION_ELIMINAR_SALA ="P15DELETESALA";
    public final static String PETICION_CREAR_SALA = "P16ADDSALA";
    public final static String PETICION_UPDATE_SALA = "P17UPDATESALA";
    public final static String PETICION_CREAR_EMPLEADO = "P18ADDEMPLEADO";
    public final static String PETICION_MOSTRAR_CLIENTES_POR_LUDOTECA = "P19SHOWCLIENTES";
    public final static String PETICION_CREAR_CLIENTE_MAYOR = "P20ADDCLIENTEMAYOR";
    public final static String PETICION_UPDATE_CLIENTE_MAYOR = "P21UPDATECLIENTEMAYOR";
    public final static String PETICION_ELIMINAR_CLIENTE = "P22DELETECLIENTE";
    public final static String PETICION_CREAR_CLIENTE_MENOR = "P23ADDCLIENTEMENOR";
    public final static String PETICION_UPDATE_CLIENTE_MENOR = "P24UPDATECLIENTEMENOR";
    public final static String PETICION_MOSTRAR_PREINSCRIPCION_POR_LUDOTECA = "P25SHOWPREINSCRIPCIONES";
    public final static String PETICION_VALIDAR_INSCRIPCION = "P26VALIDATECLIENTE";
    public final static String PETICION_MOSTRAR_TIPOS_ACTIVIDADES = "P27MOSTRARACTIVIDADES";
    public final static String PETICION_OBTENER_CATEGORIAS = "P28OBTENERCATEGORIAS";
    public final static String PETICION_OBTENER_SALAS = "P29OBTENERSALAS";
    public final static String PETICION_CREAR_NUEVO_TIPO_ACTIVIDAD = "P30ADDNUEVOTIPO";
    public final static String PETICION_OBTENER_TIPO = "P31OBTENERTIPO";
    public final static String PETICION_UPDATE_TIPO_ACTIVIDAD = "P32UPDATETIPO";
    public final static String PETICION_ELIMINAR_TIPO_ACTIVIDAD = "P33DELETETIPO";
    public final static String PETICION_OBTENER_EMPLEADOS_TIPO_ACTIVITY = "P34OBTENEREMPLEADOS";
    public final static String PETICION_OBTENER_TIPO_X_LUDOTECA = "P35OBTENERTIPOSXLUDOTECA";
    public final static String PETICION_CREAR_PLANNING = "P36ADDPLANNING";
    public final static String PETICION_CREAR_ACTIVIDAD_UNICA = "P37ADDACTIVIDADUNICA";
    public final static String PETICION_OBTENER_ALL_ACTIVIDADES_X_LUDOTECA = "P38OBTENERACTIVIDADES";
    public final static String PETICION_ELIMINAR_ACTIVIDAD_UNICA = "P39ELIMINARACTIVIDADUNICA";
    public final static String PETICION_ELIMINAR_ACTIVIDAD_PLANIFICADA ="P40ELIMINARACTIVIDADPLANIFICADA";
    public final static String PETICION_ELIMINAR_EMPLEADO = "P41DELETEEMPLEADO";
    public final static String PETICION_UPDATE_EMPLEADO = "P42UPDATEEMPLEADO";
    public final static String PETICION_OBTENER_ACTIVIDADES_CLIENTES_PLANIFICADAS = "P43SHOWCLIENTEXACTIVIDADESPLANIFICADAS";
    public final static String PETICION_OBTENER_ACTIVIDADES_CLIENTES_UNICAS = "P44SHOWCLIENTEXACTIVIDADESUNICAS";
    public final static String PETICION_PERFIL_EMPLEADO = "P45SHOWPERFILEMPLEADO";
    public final static String PETICION_OBTENER_ACTIVIDADES_X_EMPLEADO = "P46SHOWACTIVIDADESXEMPLEADO";
    public final static String PETICION_MAPA_LUDOTECAS_MOVIL = "P47SHOWLUDOTECASMOVIL";
    public final static String PETICION_REGISTRO_MAYOR_MOVIL = "P48REGISTROMAYORMOVIL";
    public final static String PETICION_REGISTRO_MENOR_MOVIL = "P49REGISTROMENORMOVIL";
    public final static String PETICION_LOGIN_CLIENTE_MOVIL = "P50LOGINCLIENTEMOVIL";
    public final static String PETICION_OBTENER_PLANNINGS_X_LUDOTECA = "P51SHOWPLANNINGXLUDOTECA";
    public final static String PETICION_OBTENER_INFO_PLANNING = "P52SHOWINFOPLANNING";
    public final static String PETICION_UPDATE_PLANNING = "P53UPDATEPLANNING";
    public final static String PETICION_ELIMINAR_PLANNING = "P54DELETEPLANNING";
    public final static String PETICION_UPDATE_ACTIVIDAD_UNICA = "P55UPDATEACTIVIDADUNICA";
    public final static String PETICION_UPDATE_ACTIVIDAD_RECURRENTE = "P56UPDATEACTIVIDADRECURRENTE";
    public final static String PETICION_INSCRIBIRSE_LUDOTECA_MOVIL = "P57INSCRIBIRSELUDOTECA";
    public final static String PETICION_OBTENER_ACTIVIDADES_LUDOTECA_MOVIL = "P58OBTENERACTIVIDADESLUDOTECA";
    public final static String PETICION_INSCRIBIRSE_ACTIVIDAD_LUDOTECA_MOVIL = "P59INSCRIBIRSEACTIVIDADLUDOTECA";
    public final static String PETICION_PAGO_ACTIVIDAD_REALIZADA_MOVIL ="P60PAGOACTIVIDADREALIZADA";
    public final static String PETICION_OBTENER_ACTIVIDADES_INSCRITAS_MOVIL = "P61OBTENERACTIVIDADESINSCRITAS";
    public final static String PETICION_ABANDONAR_ACTIVIDAD_MOVIL = "P62ABANDONARACTIVIDAD";
    public final static String PETICION_OBTENER_ESTADO_CLIENTE_MOVIL = "P63OBTENERESTADOCLIENTE";
    public final static String PETICION_ACTUALIZAR_CLIENTE_MENOR_MOVIL = "P64ACTUALIZARCLIENTEMENOR";
    public final static String PETICION_ACTUALIZAR_CLIENTE_MAYOR_MOVIL = "P65ACTUALIZARCLIENTEMAYOR";
    
    
    
    //MENSAJES  CORRECTO
    public final static String PETICION_LOGIN_CORRECTO = "C1LOGINCORRECTO";
    public final static String PETICION_LOGIN_CORRECTO_ADMIN = "C2LOGINADMIN";
    public final static String PETICION_LOGIN_CORRECTO_DUEÑO = "C3LOGINDUEÑO";
    public final static String PETICION_LOGIN_CORRECTO_EMPLEADO ="C34LOGINEMPLEADO";
    public final static String PETICION_CREAR_PROPIETARIO_CORRECTA = "C4ADDPROPIETARIO";
    public final static String PETICION_MOSTRAR_PROPIETARIOS_CORRECTO = "C5SHOWPROPIETARIOS";
    public final static String PETICION_ELIMINAR_PROPIETARIO_CORRECTO = "C6DELETEPROPIETARIO";
    public final static String PETICION_CREAR_LUDOTECA_CORRECTA = "C7ADDLUDOTECA";
    public final static String PETICION_MOSTRAR_LUDOTECAS_CORRECTA = "C8SHOWLUDOTECAS";
    public final static String PETICION_MOSTRAR_LUDOTECAS_POR_PROPIETARIO_CORRECTA = "C9SHOWLUDOTECASPROPIETARIO";
    public final static String PETICION_MOSTRAR_EMPLEADOS_POR_LUDOTECA_CORRECTO = "C10SHOWEMPLEADOSXLUDOTECA";
    public final static String PETICION_MOSTRAR_EDITAR_PROPIETARIO_CORRECTO = "C11SHOWEDITPROPIETARIO";
    public final static String PETICION_EDITAR_PROPIETARIO_CORRECTO = "C12UPDATEPROPIETARIO";
    public final static String PETICION_ELIMINAR_LUDOTECA_CORRECTO = "C13DELETELUDOTECA";
    public final static String PETICION_MOSTRAR_SALAS_POR_LUDOTECA_CORRECTO = "C14SHOWXLUDOTECAS";
    public final static String PETICION_ELIMINAR_SALA_CORRECTO = "C15DELETESALA";
    public final static String PETICION_CREAR_SALA_CORRECTO = "C16ADDSALA";
    public final static String PETICION_UPDATE_SALA_CORRECTO = "C17UPDATESALA";
    public final static String PETICION_CREAR_EMPLEADO_CORRECTO = "C18ADDEMPLEADO";
    public final static String PETICION_MOSTRAR_CLIENTES_POR_LUDOTECA_CORRECTO = "C19SHOWCLIENTES";
    public final static String PETICION_CREAR_CLIENTE_MAYOR_CORRECTA = "C20ADDCLIENTEMAYOR";
    public final static String PETICION_UPDATE_CLIENTE_MAYOR_CORRECTO = "C21UPDATECLIENTEMAYOR";
    public final static String PETICION_ELIMINAR_CLIENTE_CORRECTO = "C22DELETECLIENTE";
    public final static String PETICION_CREAR_CLIENTE_MENOR_CORRECTO = "C23ADDCLIENTEMENOR";
    public final static String PETICION_UPDATE_CLIENTE_MENOR_CORRECTO = "C24UPDATECLIENTEMENOR";
    public final static String PETICION_MOSTRAR_PREINSCRIPCION_POR_LUDOTECA_CORRECTO = "C25SHOWPREINSCRIPCIONES";
    public final static String PETICION_VALIDAR_INSCRIPCION_CORRECTO = "C26VALIDATECLIENTE";
    public final static String PETICION_MOSTRAR_TIPOS_ACTIVIDADES_CORRECTO = "C27MOSTRARACTIVIDADES";
    public final static String PETICION_CREAR_NUEVO_TIPO_ACTIVIDAD_CORRECTO = "C30ADDNUEVOTIPO";
    public final static String PETICION_UPDATE_TIPO_ACTIVIDAD_CORRECTO = "C32UPDATETIPO";
    public final static String PETICION_ELIMINAR_TIPO_ACTIVIDAD_CORRECTO = "C33DELETETIPO";
    public final static String PETICION_CREAR_PLANNING_CORRECTO = "C36ADDPLANNING";
    public final static String PETICION_CREAR_ACTIVIDAD_UNICA_CORRECTO = "C37ADDACTIVIDADUNICA";
    public final static String PETICION_ELIMINAR_ACTIVIDAD_UNICA_CORRECTO = "C39ELIMINARACTIVIDADUNICA";
    public final static String PETICION_ELIMINAR_ACTIVIDAD_PLANIFICADA_CORRECTO ="C40ELIMINARACTIVIDADPLANIFICADA";
    public final static String PETICION_ELIMINAR_EMPLEADO_CORRECTO = "C41DELETEEMPLEADO";
    public final static String PETICION_UPDATE_EMPLEADO_CORRECTO = "C42UPDATEEMPLEADO";
    public static final String PETICION_MAPA_LUDOTECAS_MOVIL_CORRECTA = "C47SHOWLUDOTECASMOVILCORRECTA";
    public static final String PETICION_REGISTRO_MAYOR_MOVIL_CORRECTO = "C48REGISTROMAYORMOVILCORRECTO";
    public final static String PETICION_REGISTRO_MENOR_MOVIL_CORRECTO = "C49REGISTROMENORMOVIL";
    public final static String PETICION_LOGIN_CLIENTE_MOVIL_CORRECTO = "C50LOGINCLIENTEMOVIL";
    public final static String PETICION_OBTENER_PLANNINGS_X_LUDOTECA_CORRECTO = "C51SHOWPLANNINGXLUDOTECA";
    public final static String PETICION_UPDATE_PLANNING_CORRECTO = "C53UPDATEPLANNING";
    public final static String PETICION_ELIMINAR_PLANNING_CORRECTO = "C54DELETEPLANNING";
    public final static String PETICION_UPDATE_ACTIVIDAD_UNICA_CORRECTO = "C55UPDATEACTIVIDADUNICA";
    public final static String PETICION_UPDATE_ACTIVIDAD_RECURRENTE_CORRECTO = "C56UPDATEACTIVIDADRECURRENTE";
    public final static String PETICION_INSCRIBIRSE_LUDOTECA_MOVIL_CORRECTO_INSCRITO = "C57INSCRIBIRSELUDOTECAINSCRITO";
    public final static String PETICION_INSCRIBIRSE_LUDOTECA_MOVIL_CORRECTO_PREINSCRITO = "C57INSCRIBIRSELUDOTECAPREINSCRITO";
    public final static String PETICION_OBTENER_ACTIVIDADES_LUDOTECA_MOVIL_CORRECTO = "C58OBTENERACTIVIDADESLUDOTECA";
    public final static String PETICION_INSCRIBIRSE_ACTIVIDAD_LUDOTECA_MOVIL_CORRECTO = "C59INSCRIBIRSEACTIVIDADLUDOTECA";
    public final static String PETICION_OBTENER_ACTIVIDADES_INSCRITAS_MOVIL_CORRECTO ="C61OBTENERACTIVIDADESINSCRITAS";
    public final static String PETICION_ABANDONAR_ACTIVIDAD_MOVIL_CORRECTO = "C62ABANDONARACTIVIDAD";
    public final static String PETICION_ACTUALIZAR_CLIENTE_MENOR_MOVIL_CORRECTO = "C64ACTUALIZARCLIENTEMENOR";
    public final static String PETICION_ACTUALIZAR_CLIENTE_MAYOR_MOVIL_CORRECTO = "C65ACTUALIZARCLIENTEMAYOR";


    //MENSAJE ERROR
    public final static String PETICION_LOGIN_ERROR = "E1LOGINERROR";        
    public final static String PETICION_CREAR_PROPIETARIO_ERROR = "E2ADDPROPIETARIO";
    public final static String PETICION_ELIMINAR_PROPIETARIO_ERROR = "E3DELETEPROPIETARIOERROR";
    public final static String PETICION_CREAR_LUDOTECA_ERROR = "E4DELETELUDOTECA";
    public final static String PETICION_EDITAR_PROPIETARIO_ERROR = "E5UPDATEPROPIETARIOERROR";
    public final static String PETICION_ELIMINAR_LUDOTECA_ERROR = "E6DELETELUDOTECA";    
    public final static String PETICION_ELIMINAR_SALA_ERROR = "E7DELETESALA";
    public final static String PETICION_CREAR_SALA_ERROR = "E8ADDSALA";
    public final static String PETICION_UPDATE_SALA_ERROR = "E9UPDATESALA";
    public final static String PETICION_CREAR_EMPLEADO_ERROR = "E10ADDEMPLEADO";
    public final static String PETICION_CREAR_CLIENTE_MAYOR_ERROR = "E11ADDCLIENTEMAYOR";
    public final static String PETICION_UPDATE_CLIENTE_MAYOR_ERROR = "E12UPDATECLIENTEMAYOR";
    public final static String PETICION_ELIMINAR_CLIENTE_ERROR = "E13DELETECLIENTE";
    public final static String PETICION_CREAR_CLIENTE_MENOR_ERROR = "E14ADDCLIENTEMENOR";
    public final static String PETICION_UPDATE_CLIENTE_MENOR_ERROR = "E15UPDATECLIENTEMENOR";
    public final static String PETICION_VALIDAR_INSCRIPCION_ERROR = "E16VALIDATECLIENTE";
    public final static String PETICION_CREAR_NUEVO_TIPO_ACTIVIDAD_ERROR = "E30ADDNUEVOTIPO";
    public final static String PETICION_UPDATE_TIPO_ACTIVIDAD_ERROR = "E32UPDATETIPO";
    public final static String PETICION_ELIMINAR_TIPO_ACTIVIDAD_ERROR = "E33DELETETIPO";
    public final static String PETICION_CREAR_PLANNING_ERROR = "E36ADDPLANNING";
    public final static String PETICION_CREAR_ACTIVIDAD_UNICA_ERROR = "E37ADDACTIVIDADUNICA";
    public final static String PETICION_ELIMINAR_ACTIVIDAD_UNICA_ERROR = "E39ELIMINARACTIVIDADUNICA";
    public final static String PETICION_ELIMINAR_ACTIVIDAD_PLANIFICADA_ERROR = "E40ELIMINARACTIVIDADPLANIFICADA";
    public final static String PETICION_ELIMINAR_EMPLEADO_ERROR = "E41DELETEEMPLEADO";
    public final static String PETICION_UPDATE_EMPLEADO_ERROR = "E42UPDATEEMPLEADO";
    public final static String PETICION_REGISTRO_MAYOR_MOVIL_ERROR = "E48REGISTROMAYORMOVILERROR";
    public final static String PETICION_REGISTRO_MENOR_MOVIL_ERROR = "E49REGISTROMENORMOVIL";
    public final static String PETICION_UPDATE_PLANNING_ERROR = "E53UPDATEPLANNING";
    public final static String PETICION_ELIMINAR_PLANNING_ERROR = "E54DELETEPLANNING";
    public final static String PETICION_UPDATE_ACTIVIDAD_UNICA_ERROR = "E55UPDATEACTIVIDADUNICA";
    public final static String PETICION_UPDATE_ACTIVIDAD_RECURRENTE_ERROR = "E56UPDATEACTIVIDADRECURRENTE";
    public final static String PETICION_INSCRIBIRSE_LUDOTECA_MOVIL_ERROR_INSCRITO = "E57INSCRIBIRSELUDOTECAINSCRITO";
    public final static String PETICION_INSCRIBIRSE_LUDOTECA_MOVIL_ERROR_NO_CONFIRMADO = "E57INSCRIBIRSELUDOTECANOCONFIRMADO";
    public final static String PETICION_INSCRIBIRSE_ACTIVIDAD_LUDOTECA_MOVIL_ERROR_PREINSCRITO = "E59INSCRIBIRSEACTIVIDADLUDOTECAPREINSCRIPCION";
    public final static String PETICION_INSCRIBIRSE_ACTIVIDAD_LUDOTECA_MOVIL_ERROR_VALIDAR = "E59INSCRIBIRSEACTIVIDADLUDOTECAVALIDAR";
    public final static String PETICION_INSCRIBIRSE_ACTIVIDAD_LUDOTECA_MOVIL_ERROR_INSCRIPCIONLUDOTECA = "E59INSCRIBIRSEACTIVIDADLUDOTECAINSCRIPCION";
    public final static String PETICION_INSCRIBIRSE_ACTIVIDAD_LUDOTECA_MOVIL_ERROR_INSCRIPCIONACTIVIDAD = "E59INSCRIBIRSEACTIVIDADLUDOTECAINSCRIPCIONACTIVIDAD";
    public final static String PETICION_INSCRIBIRSE_ACTIVIDAD_LUDOTECA_MOVIL_ERROR_SINESPACIO = "E59INSCRIBIRSEACTIVIDADLUDOTECAESPACIO";
    public final static String PETICION_ABANDONAR_ACTIVIDAD_MOVIL_ERROR = "E62ABANDONARACTIVIDAD";
    public final static String PETICION_ACTUALIZAR_CLIENTE_MENOR_MOVIL_ERROR = "E64ACTUALIZARCLIENTEMENOR";
    public final static String PETICION_ACTUALIZAR_CLIENTE_MAYOR_MOVIL_ERROR = "E65ACTUALIZARCLIENTEMAYOR";

    
}
